### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by okonomiyaki3000** [fabiospampinato/notable#14]
Cool app. Probably the nicest interface I've seen in one of these. 

A key feature for me that seems to be missing is export. Preferably to PDF but HTML is OK too. I want to be able to write up some stuff quickly in MD and spit out a document that I can send out to other people. Probably I'm not the only one.

**Comment by fabiospampinato** [comment]
> Cool app. Probably the nicest interface I've seen in one of these.

Thank you!

Some exporting options should definitely be added, thanks for the suggestion.

In anyone would like to help with this I'd me happy to consider a PR for it.

**Comment by fabiospampinato** [comment]
The following export formats should be implemented:

- [ ] Markdown
- [ ] HTML
- [ ] PDF

**Comment by fabiospampinato** [comment]
I've just added support for exporting to HTML: https://github.com/fabiospampinato/notable/commit/1501694e4c6b8f46bb19389889a54cbbafc6800f

It's by no means perfect but as an initial implementation it's pretty good:

- Attachments are exported
- Metadata is exported
- Syntax highlighting, KaTeX formulas and mermaid charts are preserved
- Images are base64 encoded for better portability

Enojy 👍

**Comment by miathedev** [comment]
Exporting it into a pdf would be really useful. Thats a feature im missing. Since the LaTeX feature has been added - theres a lot more need for this being able to export notes into pdf (for example im writing notes from my lectures into notable).

Yes of course i could export the html into pdf with my web-browser. But it would be a lot more user-friendly doing in notable directly.

**Comment by RomanKornev** [comment]
@miathedev Exporting to PDF is already added to master branch.

> The following export formats should be implemented:
> 
> * [x]  Markdown
> * [x]  HTML
> * [x]  PDF

**Comment by matthijsvp** [comment]
Currently, (at least) the Mac version exports the note into a new folder. I think just exporting the single file to the folder that's selected would be more regular behaviour.

**Comment by fabiospampinato** [comment]
@matthijsvp I think the current approach is superior generally, otherwise you're going to have problems with conflicting paths. Long-term though what you really want is to be able to share a link, that'd be much more ergonomic to use.

**Comment by sachit-n** [comment]
I would really love to be able to export to pdf without creation of a unique folder everytime. Would prefer it to automatically replace the older version. I use this tool called backup and sync by Google Drive, and having this feature would allow me to continually update documents I have shared with others via drive links automatically. Presently, I have to manually open the folder and copy it outside every time. I believe this is more user-friendly

**Comment by fabiospampinato** [comment]
@sachit-n that's not more _consistently_ user friendly though, let's say you're exporting notes to the desktop, should we fill it with potentially hundreds of things in case you're exporting lots of notes with attachments?

I think a better option for your use case would be to allow printing directly #454, so that you can export only the single file, without wrapping folders and attachments. Would that work for you?

**Comment by sachit-n** [comment]
Oh, I haven't yet exported any of my notes with attachments. Yes, I believe the print feature will allow to save as pdf, and will work for me totally. Single note export if there are no attachments would be great too. Another option eventually could be to have a settings/preferences window that can be opened from the app, and let the user select the option to export notes to a new folder or not. The change data directory, theme options may also be part of the settings window (along with any other future features/customization options)
