### ISSUE TITLE
Some tags have unmodifiable certain css properties

### ISSUE THREAD

**Issue by D-Maxwell** [fabiospampinato/notable#1673]
`del` and `ins` should not have their `background-color` defined as `!important` as it makes no difference vanilla-wise, yet is problematic for custom styling. The same problem may exist on other tags, however I haven't taken the time to list those for which I had found this to be the case.

**Comment by MMK21Hub** [comment]
Note that almost all colors in the app are defined this way: it's somewhat annoying when writing custom CSS, but it simply means you have to remember to use `!important` whenever you edit a color.

**Comment by MMK21Hub** [comment]
I've just double-checked the Discord server and it looks like Fabio has revamped the styling system for the next beta, so we won't have to worry about `!important` anymore. :tada: Here's [the relevant conversation](https://canary.discord.com/channels/715934079559663646/721056044784025653/1052531254857318430):
!["Yeah that all got rewritten from scratch actually, it hasn't shipped yet but the new system is built upon CSS variables. I'm using !important for themes because I was overriding colors in components that weren't meant to be themed, the new system should be easier to theme." - @fabiospampinato in #feedback](https://user-images.githubusercontent.com/50421330/228935909-a1573cf3-0981-4dd9-a406-8d53daeeb862.png)

**Comment by D-Maxwell** [comment]
Neat. Looking forward to it.
