### ISSUE TITLE
Jump links/bookmarks/table of contents don't work in rendered notes

### ISSUE THREAD

**Issue by CoreParadox** [fabiospampinato/notable#181]
For example, a link such as this:
`[Lorem ipsum](#lorem-ipsum)`

should be able to jump to a header like this:
`## Lorem Ipsum`
or like this:
`<a name="lorem-ipsum"/>`

However clicking the links results in no action.

**Comment by fabiospampinato** [comment]
@CoreParadox I don't think this is valid html:

```
<a name="lorem-ipsum"/>
```

That's should probably be this instead:

```
<a href="#lorem-ipsum"/>
```

**Comment by CoreParadox** [comment]
I believe using `<a href="#lorem-ipsum"/>` should jump to `<a name="lorem-ipsum"/>` in a standard html page.

**Comment by fabiospampinato** [comment]
@CoreParadox I've never seen an `a` tag with a `name` attribute, [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) isn't listing the `a` tag in the list of the tags the support the `name` attribute either. Is this in any Markdown spec maybe?

**Comment by CoreParadox** [comment]
https://www.w3.org/MarkUp/1995-archive/Elements/A.html
name is optiona, but if it's there it lets the anchor tag to be the destination of a link. name's value is used as the identifier the a tag.

**Comment by fabiospampinato** [comment]
@CoreParadox weird, it works.

**Comment by ShatteredMotion** [comment]
`name` is obsolete as of HTML5, using `id` has the exact same result:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-name

**Comment by mikaelmello** [comment]
I'd like to know if this feature is expected to be implemented soon, thanks!

**Comment by fabiospampinato** [comment]
@mikaelmello It's not in the [Next](https://github.com/fabiospampinato/notable/milestone/1) milestone, but if somebody submits a PR for this it may get included in the next release.

**Comment by mikaelmello** [comment]
I will try to take a look into it, probably tomorrow. I haven't read the codebase yet, could you point me in any useful direction for this issue? e.g. relevant files or functions.

**Comment by fabiospampinato** [comment]
@mikaelmello I'm not exactly sure what the relevant function could be. Maybe if [this](https://github.com/fabiospampinato/notable/blob/master/src/main/windows/main.ts/#L410) function gets called it should check if we are actually trying to scroll to an element or opening an external url.

**Comment by mikaelmello** [comment]
I guess checking if the first character equals to `#` would be sufficient. Do you agree?

**Comment by apisarenco** [comment]
I'm not very good with React or Electron, but here's what I achieved so far, that SHOULD have worked, except it doesn't probably because of some events that I can't find.

The generated HTML should have worked from the start, except that anchors (`[Anchor Name](#anchor-link)`) should generate `<a href="#anchor-link">Anchor Name</a>`, but it was also inserting a `target="_blank"` in there. So I cleared it.

[src/renderer/utils/markdown.ts ](/blob/master/src/renderer/utils/markdown.ts) on line 133 I defined
```
    anchorLink () {
      return [
        { // Link Button
          type: 'output',
          regex: `<a(.*?)href="(#[^"]+)"(.*?)>`,
          replace ( match, $1, $2, $3 ) {
            const prefix = $1.replace(`target="_blank"`, '')
            const sufffix = $3.replace(`target="_blank"`, '')
            return `<a${prefix}href="${$2}" class="note test"${sufffix}>`;
          }
        }
      ]
    },
```
and then add it to the appropriate place in `getConverter ()` function.

then I got a valid HTML that should follow the anchor link. And it did once, but that was a faulty start or something, because it didn't work afterwards. If I enter from the console `window.location.hash='#my-anchor'`, it works and I do get to that anchor. But if I click on what appears to be a proper `<a href="#my-anchor">Anchor Link</a>`, nothing's happening.

Could it be that React monopolizes event handlers and cancels any subsequent events like the native event of going to that position on the page? Could it be doing that just for URL hash to make sure there is no annoying scrolling to the top of the page? If so, then a simple addition of an event, that's placed on an `<a>` element, and checks if the clicked URL has a different hash than the `window.location.hash`, then it should update the `window.location.hash` to the new one. That would scroll to where it needs to.

If this event were to also run when handling `file://path/to/whatever#hash` it would also enable us to link to particular places in a file.


How this works in markdown:

```markdown
* (Chapter)[#chapter]
  * (Sub-Chapter 2)[#sub-chapter-2]
  * (Notes)[#notes]

# Chapter
...
## Sub-Chapter 2
...
## Notes
```

That would be its basic implementation, that's standard and compatible with all the other markdown editors that I know of.

A non-standard, "plus" feature would be to just mention the link by the title of the header. Like the example above, but just write this for the link:

```
[](@anchor/Sub-Chapter 2)
```

**Comment by fabiosirna** [comment]
Hello, 
@fabiospampinato has this been fixed?
I was trying to add a Table of Contents in a document I'm working on, but I have the same issue as for previous messages.

**Comment by fabiospampinato** [comment]
@shew00 thanks for the help, it sounds like a easy fix, I'm adding it to the Next milestone.
