### ISSUE TITLE
Is it possible to support image in relative path style

### ISSUE THREAD

**Issue by xtuer** [fabiospampinato/notable#205]
In Notable using images with the format `[](@attachment/avatar.jpg)` which causes the third MD editor such as **Typora** cannot recognize the image. 
Is it possible to support image in relative path style as `[](../attachments/avatar.jpg)`?

**Comment by fabiospampinato** [comment]
Absolutely, I'll add support for this.

**Comment by fabiospampinato** [comment]
Implemented, and you get all the goodies too:

<img width="361" alt="screen shot 2019-01-17 at 21 19 10" src="https://user-images.githubusercontent.com/1812093/51346302-93995d00-1a9d-11e9-803b-94c41c5a24ce.png">

**Comment by xtuer** [comment]
Seems this feature is not released in the version 1.2.0.
And "Inspect Element" menu item is not found.

**Comment by amelandri** [comment]
I confirm that it seems not present in version 1.2.0. (I'm on Windows 10)

**Comment by fabiospampinato** [comment]
@xtuer @amelandri can you paste here the exact code you're using but it's not working? I've just tried the following and it works as intended for me:

```
![](../attachments/icon_small.png)
```

> And "Inspect Element" menu item is not found.

That's an unrelated thing that's only supposed to be visible during development.

**Comment by amelandri** [comment]
Woah, it works. I'm a bit confused, because I'm pretty sure that I did the same thing this morning and it didn't work.

**Comment by xtuer** [comment]
By the way, `<img>` also doesn't work, such as 

```
<img src="../attachments/icon_small.png" width="100">
```

Want to use img tag to control the image size.

**Comment by fabiospampinato** [comment]
> `![](img/chart.png)`

It should be `![](./img/chart.png)` instead.

**Comment by jhconning** [comment]
> 
> `<img src="../attachments/chart.png" width=574>` doesn't work.
> 
> Good catch, I forgot to add support for this syntax too.

Was support for this added?  This issue was closed but It doesn't seem to work.

This works:

`<img src="@attachment/icon.png" width="400">`

but this doesn't:

`<img src="../attachment/icon.png" width="400">`

Loving notable's elegant and clever design,  but still looking for the right syntax that will allow the markdown files it uses to also work nicely with Typora. and other markdown needs.

**Comment by fabiospampinato** [comment]
> Was support for this added? This issue was closed but It doesn't seem to work.

Yes. You're pointing to the "attachment" directory which doesn't exist, it's called "attachments" with an s at the end.

**Comment by fabiospampinato** [comment]
It happens, I make dump mistakes all the time, the other day I realized I was calling "fixtures" "mocks" for years  🤦‍♂️

**Comment by jhconning** [comment]
fixtures vs. mocks seems more forgivable (I had to look up both terms) but from now on I'll be sure to check my spelling more carefully before posting an issue 😄

**Comment by gynet** [comment]
Has this been merged and released. It seems like ![](img/chart.png) not working on  1.8.2

**Comment by fabiospampinato** [comment]
@gynet I had only added support for relative paths starting with a dot, so like `./img/chart.png`. Now I've just added support for relative paths that omit the dot as well, and the fix will be available in the next release, however using these kinds of paths is strongly discouraged because they can be ambiguous, for example if I write: `![](google.com/icon.png)` should that point to Google or should we assume there's a folder named "google.com"? In order to avoid ambiguities the dot should always be provided for relative paths.

**Comment by gynet** [comment]
Thanks. @fabiospampinato. It can be ambitious. But I assume most ppl would add protocol name as the prefix if they want to refer remote resources. Not sure about other markdown engines, but seems like GitHub and Typora works fine without the dot. Would suggest to follow the same behaviors as other engines

**Comment by dchatterjee** [comment]
Hi, I am using 1.8.4 but it is still not working.. 
![](@attachments/Clipboard_2020-06-10-13-59-54.png)

the attachments folder is created automatically when I try to past the screenshot in clipboard.

root
  | - attachments
  |          | - Clipboard_2020-06-10-13-59-54.png
  | - notes
  |       | - note.md

**Comment by fabiospampinato** [comment]
@dchatterjee can you share the content of `note.md` that doesn't work for you?
