### ISSUE TITLE
Feature request: showing folder structure in side bar

### ISSUE THREAD

**Issue by OliverLew** [fabiospampinato/notable#210]
I know there is a previous issue #54 very similar to this, but I think mine is still a little different.

My thought is only to **show** folder structure in the side bar, and it has nothing to do with messing up either the tags or notebooks or creating folders by the app. This might provide a alternative organizing method for someone who doesn't like 1-level folder idea (or someone who wants to use this app to edit their existing note files stored in multiple-level folders).

So the folders can't be changed inside the app, only manually organized by users. Users just navigate through them. (I think the idea is not bad because currently user also cannot change anything through the sidebar, where I like the simplicity, and this fits right into it)

I am not quite a programmer myself, but I guess this may be not hard to implement. Maybe it can be done by treating the relative path of the files to the 'notes' folder as a special kind of 'tag', and use similar code for the 'Tags' section in the side bar to make a 'Folders' section.

**Comment by fabiospampinato** [comment]
I don't think there's a place for this in Notable, by design the structure comes from the tags, if you want to structure your notes via directories you might be better off with [Typora](https://typora.io).

The problem of editing/finding Notable notes on mobile will be solved as soon as we make mobile apps #23, the problem of editing the notes via third-party tools will become increasingly less important as we improve our own and add support for plugins #128.
