### ISSUE TITLE
Double click tags in the tree to expand / collapse

### ISSUE THREAD

**Issue by LukeDefeo** [fabiospampinato/notable#25]
This would help with usability of the interface

**Comment by GCSBOSS** [comment]
I can try and do it if I knew where to attach the handler. Do you have any directions? I have found the file `src/renderer/components/main/sidebar/tag_group.tsx`

**Comment by johnletey** [comment]
I'd also love to be able to expand/collapse the notebooks in the tree, as well as the tags!

**Comment by fabiospampinato** [comment]
@GCSBOSS currently there seems to be a problem with a command needed for generating the CSS, you're going to have a hard time implementing this without a proper interface.

In order to implement this you'd probably want a file like [this](https://github.com/fabiospampinato/notable/blob/master/src/renderer/components/main/extra/preview_plugins.tsx) and a more resilient [toggleCollapse](https://github.com/fabiospampinato/notable/blob/master/src/renderer/containers/main/tag.ts/#L69) function (it currently kind of assumes the note is actually collapsable.

**Comment by GCSBOSS** [comment]
Thanks. Somethings like `__tagDblclick`? I am probably out in the rain by not being familiar with react.

**Comment by fabiospampinato** [comment]
@GCSBOSS Yes the handler name could have that name, I usually prefix my event handlers with 2 underscores.

**Comment by tforward** [comment]
@fabiospampinato If you don't move the mouse and double click semi-rapidly it will stop the collapsing behavior until you move the mouse again, or make really slow deliberate clicks

**Comment by fabiospampinato** [comment]
@tforward I can't reproduce this.

**Comment by tforward** [comment]
@fabiospampinato Hmm, Specifically I'm on the Grey area of Notebooks  First double-click works, Second double-click sometimes works, third does not. Again this is a "fast" double click action without moving the mouse. I have another machine I can test it on I'll let you know what I find

**Comment by fabiospampinato** [comment]
@tforward are you performing those double-clicks in a rapid sequence?

**Comment by tforward** [comment]
sort of, I would not say excessive. Same rate of clicking speed in other
programs interacts with UI without issue

**Comment by fabiospampinato** [comment]
@tforward can you open a separate issue about this? It would be great if you could also record a small screencast about this.
