### ISSUE TITLE
Add Trilium to comparison table

### ISSUE THREAD

**Issue by Droyk** [fabiospampinato/notable#263]
###### I know this is a stupid question, forgive me.
What are the differences? 
I am new to this, I just found out about both of these apps, from my perspective they both look good so as a power user what's your opinion about these?
care clarify the differences?

https://github.com/zadam/trilium

**Comment by lukaskawerau** [comment]
I think one very important difference is that Trillium seems to be based on a SQLite database, whereas Notable works with Markdown files directly. To me, this is _the biggest_ advantage Notable has over any other knowledge base app. I don't have to rely on weird standards, hope they export well or anything. I can keep my repository of 1500+ notes in a format that will be readable _forever_, no matter which tool I use to interact with it.  
Also: corrupting thousands of individual markdown files is much harder than a single SQLite database file.  
That being said, Trillium looks really cool! There's lots of great functionality in there that I think is great, but I'll just never move away from a plain markdown file workflow.

**Comment by edenpc** [comment]
Notable definitely looks more polished than Trilium.

**Comment by Droyk** [comment]
Yeah, it would be pretty great if he could share the pros & cons about his own app in compare to notable.
So @zadam what do you say?

**Comment by zadam** [comment]
free: yes
open source: yes
cross platform: yes (linux, windows, mac, desktop web + mobile web)
no account required: yes
no wysiwyg: no
no bloat: I don't know what this means. But to consider e.g. "web clipper" (which Trilium doesn't have yet) to be bloat sounds to me weird
pretty ui: probably no 
github flavored markdown: no
code syntax highlighting: yes
attachments: yes
fuzzy search: probably no
indefinitely nestable tags: Trilium's cloning is actually more powerful (and general) than this
multi-note search & replace: no
keyboard friendly: yes
mobile app: no, but there's a web version optimized for mobile
sync: yes
vesion control: yes

However the list is pretty biased (like wysiwig is a con) but then I guess it's to be expected.

**Comment by Droyk** [comment]
Hey thanx @zadam so apart from these what do you think from your perspectivce as the main dev of trilium the most important advantage that trilium has over notable, vice-versa also & what do you think about @lukaskawerau take on this.
>I think one very important difference is that Trillium seems to be based on a SQLite database, whereas Notable works with Markdown files directly. To me, this is the biggest advantage Notable has over any other knowledge base app. I don't have to rely on weird standards, hope they export well or anything. I can keep my repository of 1500+ notes in a format that will be readable forever, no matter which tool I use to interact with it.
Also: corrupting thousands of individual markdown files is much harder than a single SQLite database file.
That being said, Trillium looks really cool! There's lots of great functionality in there that I think is great, but I'll just never move away from a plain markdown file workflow.

**Comment by fabiospampinato** [comment]
@zadam Thanks for jumping in! 

> However the list is pretty biased (like wysiwig is a con, not listing features which other apps have but notable doesn't) but then I guess it's to be expected.

The comparison table is definitely biased as it's meant to mostly showcase why I built Notable rather than using something else, for instance I don't want to use a WYSIWYG editor so I consider that a con.

As long as those other features are also important to me I can consider adding them. For instance I see Trilium has support for encrypted notes, it supports theming and it's pretty customizable (both via loading some custom CSS and via providing a Script API). Anything else in particular you'd like to see added to the table?

Commenting some of your answers:

 > no propriatery formats: if you consider sqlite & html proprietary, then I guess no

I wouldn't consider them proprietary per se, but by "no proprietary formats" I mostly mean "are my notes/metadata/attachments stored in a way that I could interact with other then by using the app?", since Trilium can export to HTML though I wouldn't see notes are particularly locked into any format.

> no bloat: I don't know what this means. But to consider e.g. "web clipper" (which Trilium doesn't have yet) to be bloat sounds to me weird

To me this means something like "are there any features that I completely don't care about? Bonus negative points if the UX suffers because of them". It's totally biased, as I mention below the comparison table. For instance I would consider Trilium Weight Tracker bloat if it were integrated into the app, but I think it's not and it's just showcasing how powerful the script API is?

> indefinitely nestable tags: Trilium's cloning is actually more powerful (and general) than this

Can you elaborate on this? Like: what can you do with Trilium's "cloning" that you can't do with indefinitely nestable tags?

Thanks again for joining the discussion, I'll add Trilium to the comparison table.

**Comment by zadam** [comment]
> The comparison table is definitely biased as it's meant to mostly showcase why I built Notable rather than using something else, for instance I don't want to use a WYSIWYG editor so I consider that a con.

Yeah, I understand this. It's just some people might mistake it for independent comparison.

> Anything else in particular you'd like to see added to the table?

I think in general advanced tagging and tag search (something like '@book @genre=scifi @year<=1950') is quite universal advanced use case.

I mentioned another one above - web clipper which is almost universally useful (who doesn't need to copy things from the web?), but comparison lists it as bloat for some reason.

> Can you elaborate on this? Like: what can you do with Trilium's cloning that you can't do with indefinitely nestable tags?

So Notable as I understand it uses these tags as its primary means of organization since it allows to a) categorize it into a tree (of tags) and b) it allows single note to be organized into several places in the tree. I think both of us consider this to be pretty important.

Trilium doesn't use tags as a way to organize notes. Instead the notes themselves form a hierarchy, with a difference from standard tree structure in the fact that any note can be "placed" into more than one place (= can have multiple parents). This has similar purpose to nestable tags - I want to be able to place a note into multiple places in the hierarchy.

Imagine I have the following note subtree:

* Harry Potter and the Philosopher's Stone
  * Review
  * Highlights

I want to put this subtree into multiple places in the hierarchy (e.g. under "Books read in 2018" and "J. K. Rowling". In Trilium "Harry Potter" note will just have multiple parents. As far as I understand (correct me if I'm wrong) this is not possible in Notable because you're tagging only single note. One possible way to do this would be to allow tags themselves be tagged (placed into hierarchy).

**Comment by zadam** [comment]
@Droyk 

One reason for the database is the scale when you're trying to do something advanced. Once you get to something like 10 000 notes, searching by e.g. label (e.g. "give me all notes with this label) can take some time. This might be tolerable if that's the only thing you're doing, but in case of trilium this is often just one of the many things scripts need to do. 10 000 might seem a lot from the point of "note taking", but what I am targetting is more "knowledge base building" over long period of times. What I'm trying to target are use cases of up to 100 000 notes.

So the natural thing to do in such a case is to build some kind of index files to speed up such operation. Maybe each label has an index file which contains list of notes tagged with such label. You'll probably want to do something like this with full text search, you also want to store some note metada in "sidecar" files (e.g. attributes, e.g. for a book publishing date). Maybe you want to add the ability to see what other notes link to a particular note - in that case you might warn a user that the note which they want to delete is referenced from somewhere else. No problem, you just add another index.

In effect you're kind of building you own little proprietary databases with custom formats. Some of it is only derived data (indexes), some of them actually store valuable data (note metadata) without a standard way to query it. Some apps went with this approach far - e.g. DokuWiki doesn't use standard RDBMS, but stores the data in flat files ... or actually in what is in reality a custom built database stored in "flat files".

Now what happens if you sync such flat file structure with indexes with e.g. Dropbox. You delete a note at work - this will of course update the related index files for e.g. labels - all these changes will be synced to Dropbox. Now you come home, but damn, internet is down. But you can still work with your notes so you change stuff, which also updates the indexes. Now your net connection comes up again, but there are sync conflicts in the label index files. Dropbox can't merge the changes, it can just ignore one change or the other. But it's just index, right? Yeah, but the app itself isn't notified of any problem (by Dropbox) so it doesn't rescan the files and it will keep working, only incorrectly.

Data consistency in general is a problem when not using a database. Trilium performs quite a number of data consistency checks during each startup to check that the data are in the expected state so the app can work with them effectively. But that's not really feasible without database - scanning each of potentially tens of thousands of files is not something we can bother user with often. And data will get into weird states with time, either with bugs in the code or some external factors (e.g. user manually playing with metadata).

**Comment by fabiospampinato** [comment]
> I think in general advanced tagging and tag search (something like '@book @Genre=scifi @year<=1950') is quite universal advanced use case.

That's a good suggestion, I'll add that.

> I mentioned another one above - web clipper which is almost universally useful (who doesn't need to copy things from the web?), but comparison lists it as bloat for some reason.

Actually I'm not even sure what a web clipper does exactly. Personally if I need some text from a webpage I just copy-paste it, and if I kind of want to take a cropped screenshot of it I do a <kbd>Cmd+Shift+4</kbd>, select the portion of the page I want, and there I have the screenshot. 

From my perspective I don't see why I would want to use a web clipper, but I guess maybe these screenshotting capabilities are a bit lacking on other OSes, or maybe a web clipper does more than that, and having a web clipper is actually valuable to many people.

> As far as I understand (correct me if I'm wrong) this is not possible in Notable because you're tagging only single note.

Thanks for the explanation. If I'm understanding this correctly in Trilium notes are basically the nodes of the tree, but they can also kind of be "cloned" by reference. 

In Notable instead each note describes some trees (or rather linked lists), via tags, the note itself is a leaf node of, and then all those trees are kind of merged together. I'm not sure if that's a clear explanation or not 🤔, basically there's no parent-child relationship between notes.

In Notable you can actually also "copy" a subtree somewhere else, for instance if there are some notes tagged with `foo/bar`, and if there are some notes tagged with `test`, so that the structure is:

- foo
  - bar 
- test

And you want to copy the "foo" tree under "test" then what you have to do is adding the `test/foo/bar` tag to the notes tagged with `foo/bar`.

I think it's a bit difficult to do this currently but the main difference here is that in Notable you'd have to update all the notes involved, in Trilium you'd only have to add another reference in the tree.

Commenting also with regards to having a database:

> But it's just index, right? Yeah, but the app itself isn't notified of any problem (by Dropbox) so it doesn't rescan the files and it will keep working, only incorrectly. 

Notable isn't actually currently keeping any metadata outside of your notes, so there's no index that can get in a broken state because we are generating the necessary indexes each time at startup. I see how this could become a problem for huge amounts of notes though.

I think one issue with Trilium's current database approach is that if the app itself doesn't provide a feature, and you don't want to code it yourself via the APIs, you're kind of stuck. To give a practical example: for some reason when I was using Evernote I also put tags in the titles, so if a note was tagged with "Foo" maybe it's title would have been "[Foo] My Note", now what do you do if you want to remove all those tags from the titles across all your notes?

In Notable you can just perform a regex search & replace with your editor of choice across your notes directory, in Evernote (and maybe Trilium as well, correct me if I'm wrong) to do this you have to export all your notes, delete all the notes from the app, perform a search & replace on the exported notes and then reimport all the notes again, which can get pretty messy pretty quickly and also I've found that it's common to export only a fraction of all the metadata the app has (in Evernote you lose the information about in which notebook each note was, and if they were trashed) so even after all this trouble you end up in a different state than you started off with, just to perform a global search & replace, which admittedly might me a niche use case though.

**Comment by zadam** [comment]
> Actually I'm not even sure what a web clipper does exactly. Personally if I need some text from a webpage I just copy-paste it, and if I kind of want to take a cropped screenshot of it I do a Cmd+Shift+4, select the portion of the page I want, and there I have the screenshot.

From my perspective it's mainly the fact you can save the content without switching to another app. Web clipper doesn't break you out of the browsing.

> Thanks for the explanation. If I'm understanding this correctly in Trilium notes are basically the nodes of the tree, but they can also kind of be "cloned" by reference.

Yes. Even though "cloning" is pretty misleading since all the parent references are equal so there's no "original" and "clone" from system perspective.

> I think it's a bit difficult to do this currently but the main difference here is that in Notable you'd have to update all the notes involved, in Trilium you'd only have to add another reference in the tree.

Yep, I think that's the main difference, but I think pretty important one. Tagging each note separately may work in this simple book case, but some of my cloned subtrees contain hundreds or thousands of notes and it's not practical to have to tag each of them separately.

> Notable isn't actually currently keeping any metadata outside of your notes, so there's no index that can get in a broken state because we are generating the necessary indexes each time at startup.

I assume you then watch the files if they are modified (by sync through Dropbox) to update the indexes. I think this has some scalability problems since OS often limits the number of files you can watch (I know my Intellij IDEA keeps bugging me that the inotify limit is too low and I should raise it).

> To give a practical example: for some reason when I was using Evernote I also put tags in the titles, so if a note was tagged with "Foo" maybe its title would have been "[Foo] My Note", now what do you do if you want to remove all those tags from the titles across all your notes?

In such a case I would create a "code note" in Trilium which uses Trilium's script API which would go over the notes and update the title if it contained it. Then I just run it from inside Trilium. All the changes will be synced automatically. This is not tested but uses real API calls:

```javascript
for (const note of await api.getEntities('SELECT * FROM notes')) {
      if (note.startsWith("[Foo]")) {
            note.title = note.title.substr(5).trim();
            await note.save();
      }
}
```

Of course this is way more involved than just search & replace, but it's also more flexible and can cover cases which are not possible with search & replace.

**Comment by fabiospampinato** [comment]
> but some of my cloned subtrees contain hundreds or thousands of notes and it's not practical to have to tag each of them separately.

From the user perspective in Notable you can do that (at least for the simplest use cases) with a few clicks and keystrokes since we ship a multi-note editor, but yeah the app could still have to update hundreds if not thousands of files which is not great.

> I assume you then watch the files during runtime if they are modified (by sync through Dropbox) to update the indexes. I think this has some scalability problems since OS often limits the number of files you can watch (I know my Intellij IDEA keeps bugging me that the inotify limit is too low and I should raise it).

Interesting 🤔 Yeah we are currently listening for changes, I'm not familiar with the OS-imposed limitations in this regard, I'll have to document myself on this, thanks for point at it.

> Of course this is way more involved than just search & replace, but it's also more flexible and can cover cases which are not possible with search & replace.

Any sort of manipulation you could do via the provided APIs you can also do just by editing the actual files in Notable. Maybe this doesn't matter much once you have some scripting support and the user is competent enough to use it, but just to give a few more examples on why I think storing notes as plain Markdown files can be good:

- I have a nice plugin in my editor of choice for formatting Markdown tables, I guess with Trilium's database approach the user would have to copy the table, paste it into the editor, format it and then copying-paste it again into the app, a minor annoyance. In notable you just open the note in the editor (<kbd>Cmd+O</kbd>), format it and that's it.

- There's currently no support for exporting notes to PDF in Notable, but if one really wanted to he could convert all notes to PDF via something like [pandoc](https://pandoc.org) in a one-liner shell script. Nobody is going to do this, but your notes are free (as in non-locked-in) enough that you can do this sorts of things if you want to.

**Comment by fabiospampinato** [comment]
> I guess that's the advantage of WYSIWYG in that you don't need to do such thing at all :-)

Hum... yes 😂. Unfortunately WYSIWYGs are not all roses and flowers (I'm not sure if this is a saying in English as well, btw I've just realized that this saying doesn't make much sense as roses are actually flowers 🤔) for me.

> But in general I agree that having notes stored as plain text does have very strong advantages and may be completely adequate approach for many use cases. What I tried above is to just explain why I think it's not a good solution for my particular needs.

 Sure, I'll be happy to let you know when/if the app becomes mature/performant enough that it can handle 1 million notes without breaking a sweat.

Thanks for joining the discussion, and for making Trilium too, it looks pretty interesting and I'll sure keep an eye on it :)

**Comment by Droyk** [comment]
>What I'm trying to support are use cases of up to 100 000 notes.

Thanx for supporting it. I loved the idea behind it.
>Actually I'm not even sure what a web clipper does exactly. Personally if I need some text from a webpage I just copy-paste it, and if I kind of want to take a cropped screenshot of it I do a Cmd+Shift+4, select the portion of the page I want, and there I have the screenshot.
From my perspective I don't see why I would want to use a web clipper, but I guess maybe these screenshotting capabilities are a bit lacking on other OSes, or maybe a web clipper does more than that, and having a web clipper is actually valuable to many people.

You are correct on windows we cannot select the portion of the page via a crosshair we can only capture the entire screen or a selected window at least not via the shortcut keys. I haven't use mac, as I just ran a simple google-fu after seeing your comment & found out that Mac users have the ability to capture the portion of the page via a crosshair that's a really useful & a power user feature sadly for us win users we don't have this kind of magic so we need to rely on some other tools like web clippers these sometimes are really time-saving & as @zadam told you 
>"you can save the content without switching to another app. Web clipper doesn't break you out of the browsing."

they also come with annotation feature in which as a user you can annotate certain parts of the image you have captured, for example, if you want to circle or emphasize an element in the shot. they also have a feature to blur some text or a portion of the page you want to hide for privacy reasons.

though things are getting better in windows 10 so now users can use a quick tool to does the same functionality as web clipper used to does.

the only reason I still use the web clipper because they provide me the functionality like upload your image directly to a 3rd part image hosting website like Imgur, unsplash & many other.   

> In such a case I would create a "code note" in Trilium which uses Trilium's script API which would go over the notes and update the title if it contained it. Then I just run it from inside Trilium. This works even for encrypted/protected notes and all the changes will be synced automatically. This is not tested but uses real API calls:
> 
> ```js
> for (const note of await api.getEntities('SELECT * FROM notes')) {
>       if (note.title.startsWith("[Foo]")) {
>             note.title = note.title.substr(5).trim();
>             await note.save();
>       }
> }
> ```
> 
> Of course this is way more involved than just search & replace, but it's also more flexible and can cover cases which are not possible with search & replace.

as @fabiospampinato said I also don't think that a normal user is competent enough to use it. The reason I am saying this because I am not.

**So finally @fabiospampinato & @zadam is it possible to get the best of both worlds.**
