### ISSUE TITLE
Quick notes switcher

### ISSUE THREAD

**Issue by divyanshu013** [fabiospampinato/notable#277]
### Feature description

This could be something like slack has (<kbd>Cmd</kbd> + <kbd>K</kbd>) or VS Code's file switcher (<kbd>Cmd</kbd> + <kbd>P</kbd>)

For example:

![image](https://user-images.githubusercontent.com/6682655/51179589-04991300-18ec-11e9-915c-fbb0e6e55085.png)

### Feature motivation

Ability to quickly switch between notes. For example sometimes I'm working on my **design** notes and want to quickly switch to my **react** note to jot down something.

Would be happy to work on this, but not sure about my timeline so I thought I would post it here.
Thanks!

**Comment by fabiospampinato** [comment]
There's some overlap with the search functionalities, what would be the advantages of this over just searching? More advanced search features should be implemented so that one could filter by tags etc.  (there should be an issue about this which I can't find).

This is also something similar to #273, which is about switching data directories though.

**Comment by divyanshu013** [comment]
I think it would speed up my workflow, not sure about how others feel about it (lesser keystrokes and faster switching). Please feel free to close it if you think this might be out of scope.

**Comment by fabiospampinato** [comment]
@divyanshu013 how would that exactly speed up your workflow for switching notes though? You're going to need a shortcut for opening the "switcher", and you need a shortcut for focusing to the search bar too, after that is just a matter of writing the query I think 🤔 VS Code's quick open feature is more useful because it lets you filter the path as well, our notes directory is flat (unless modified manually) so we don't get any advantage from that.

**Comment by divyanshu013** [comment]
Makes sense. I was mostly using the app in focus mode so didn't give the search much try. Thanks!

**Comment by bendem** [comment]
I think the real request is for the search to be fully usable from the keyboard (like the slack switcher). Search input is focusable using the keyboard, typing provides a keyboard accessible list of notes/tags, you can either switch to the note/tag you searched for or abort the search to go back to the note you were one before.

**Comment by fabiospampinato** [comment]
I'm closing in favor of #338, which is more generic.
