### ISSUE TITLE
Notable vs Typora

### ISSUE THREAD

**Issue by rattanakchea** [fabiospampinato/notable#285]
I am using Typora for my main Markdown editor. I have only used Notable for an hour and I am learning about it. There is no perfect editor to fit everyone's need.

Typora have some features that I love:
- WYSIWYG or auto-rendering of markdown to make writing less distracting from markdown syntax
- Spell check for common words.
- Maintain folder structures as is

Notable, I love these:
- Tagging, Favorites, PINNING, Attachment features
- Searching capability

Question for Notable
- does it copy all files into a one notes folder when I import other markdown files?

All files will reside inside the notes folder? In a long run, a user might have hundreds of files inside the notes folder. As an organized freak, I hate to have all files in one location without naming hierarchy.
If I switch over to a different app, I imagine having to re-organize the tagging again.

Is it a valid concern?

**Comment by fabiospampinato** [comment]
> WYSIWYG or auto-rendering of markdown to make writing less distracting from markdown syntax

Related issue: #284 

> Spell check for common words.

Related issue #108 

> Maintain folder structures as is

Related issue: #54 

Actually this should already be the case with Notable too, but we don't maintain any fancy structures when you create the new notes within the app.

> does it copy all files into a one notes folder when I import other markdown files?

I'm not sure I'm understanding this right, but when you import a note it gets copied into the notes directory, yes.

> All files will reside inside the notes folder? In a long run, a user might have hundreds of files inside the notes folder. As an organized freak, I hate to have all files in one location without naming hierarchy.
If I switch over to a different app, I imagine having to re-organize the tagging again.
> Is it a valid concern?

I think many people feel the same way as you do, most of the discussion on this has happened in the linked issue, I'd encourage you to read that, but basically organizing notes via folders comes with its downsides, downsides that I don't want to pay since I don't need this.

Perhaps in the future we could have some kind of "special" export toggle that exports your notes in the particular folder structure some people are asking for.
