### ISSUE TITLE
How many documents can he support?

### ISSUE THREAD

**Issue by absir1949** [fabiospampinato/notable#291]
It replaces the database with files，but if we have Thousands of files，Does it suport? Will it be slow?

**Comment by bendem** [comment]
You can try it by generating a bunch of files on your filesystem and then opening notable. Make sure to let us know the results of your experiments so we can take action if there are indeed performance problems.

**Comment by fabiospampinato** [comment]
> You can try it by generating a bunch of files on your filesystem and then opening notable.

Yeah that's actually what I did before releasing the app.

> How many documents can he support?

There's no hard limit really, but from my benchmarks with about 10k notes I can tell you that there are some things that scale with the number of notes, so they become slower the more notes you add:

- Start-up times and initialization
- Searching, but after the first filtering round it should be quick again

Some other things are pretty optimized already:

- The notes list actually renders only the notes you can see, so it doesn't matter much if there are 10 notes or 1 million
- Mutating a note so that the sidebar changes won't cause the entire tags structure to be recomputed

Other things are kind of unaffected by the number of notes you have:

- The editor deals with one note at a time, so even if you have 1 million notes it doesn't matter to it

I'm not 100% sure what the next bottleneck is but I remember there were lots and lots of promise-related functions being called during the benchmark. Since we are making heavy use of async functions but we are actually targeting es5 (because of some incompatibilities with some dependencies) those functions get transpiled down using state machines which are much slower than a native async/await implementation. Hence the next milestone for performance if probably targeting es2017 or something #100
